server:
  port: 9001

spring:
  application:
    name: springboot-flyway
  datasource:
    url: jdbc:mysql://localhost:3306/kvsrrliquibase?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: kvsrr
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update